input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "arvello_logstash"
    password => "${LOGSTASH_PASSWORD}"
    index => "arvello-logs-write"
    action => "create"
    data_stream => false
    ilm_enabled => false
    manage_template => false
  }
}
